"""text fields

Revision ID: 810c3120cc37
Revises: fd855bf7fe9e
Create Date: 2021-12-20 15:02:44.259223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "810c3120cc37"
down_revision = "fd855bf7fe9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("name", sa.Text(), nullable=False))
    op.add_column("books", sa.Column("name", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "name")
    op.drop_column("authors", "name")
    # ### end Alembic commands ###
