"""initialize

Revision ID: fd855bf7fe9e
Revises: 
Create Date: 2021-12-20 15:00:29.399917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd855bf7fe9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pgbench_branches')
    op.drop_table('pgbench_accounts')
    op.drop_table('pgbench_tellers')
    op.drop_table('pgbench_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgbench_history',
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=22), autoincrement=False, nullable=True)
    )
    op.create_table('pgbench_tellers',
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tbalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=84), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tid', name='pgbench_tellers_pkey')
    )
    op.create_table('pgbench_accounts',
    sa.Column('aid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=84), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('aid', name='pgbench_accounts_pkey')
    )
    op.create_table('pgbench_branches',
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=88), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bid', name='pgbench_branches_pkey')
    )
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
